// =============================================================================
// Product technical-specification data — feeds the per-product spec-sheet PDFs
// (generated by scripts/gen-spec-sheets.ts) and can also be surfaced on-page.
//
// IMPORTANT — these are TYPICAL / INDICATIVE values for a merchant-export
// specification, grounded in Codex Alimentarius, FSSAI and common trade
// (ASTA/ESA) norms for dried fruit, vegetable, herbal and hydrocolloid powders.
// They are NOT a Certificate of Analysis. Every shipment ships with a
// batch-specific COA from the processing unit; actual figures vary by crop,
// grade and drying method and must be confirmed against that COA before being
// quoted contractually. Sensory notes and nutrition are "typical values".
// =============================================================================

export interface Nutrition {
  energy: number;   // kcal per 100 g
  protein: number;  // g
  fat: number;      // g
  carb: number;     // g
  sugars: number;   // g
  fibre: number;    // g
  sodium: number;   // mg
}

export interface KV { k: string; v: string; }

export interface ProductSpec {
  appearance: string;          // physical form
  colour: string;              // characteristic colour
  odour: string;               // characteristic aroma
  taste: string;               // characteristic flavour
  mesh: string;                // typical granulation
  params?: KV[];               // product-specific physico-chemical rows
  nutrition: Nutrition;
  nutritionNote?: string;      // key nutrients worth highlighting
}

export interface CategoryDefaults {
  gradeLabel: string;
  shelfLife: string;
  micro: KV[];
  heavyMetals: KV[];
  packaging: string;
  storage: string;
  allergen: string;
  compliance: string;
}

// --- Shared blocks -----------------------------------------------------------
const MICRO_STD: KV[] = [
  { k: "Total Plate Count", v: "≤ 50,000 cfu/g" },
  { k: "Yeast & Mould", v: "≤ 1,000 cfu/g" },
  { k: "Coliforms", v: "≤ 100 cfu/g" },
  { k: "E. coli", v: "Absent in 1 g" },
  { k: "Salmonella", v: "Absent in 25 g" },
  { k: "S. aureus", v: "Absent in 1 g" },
];
// Leaf/herbal powders naturally carry a higher (but controlled) micro load.
const MICRO_HERBAL: KV[] = [
  { k: "Total Plate Count", v: "≤ 100,000 cfu/g" },
  { k: "Yeast & Mould", v: "≤ 5,000 cfu/g" },
  { k: "Coliforms", v: "≤ 100 cfu/g" },
  { k: "E. coli", v: "Absent in 1 g" },
  { k: "Salmonella", v: "Absent in 25 g" },
  { k: "S. aureus", v: "Absent in 1 g" },
];

const HEAVY_METALS: KV[] = [
  { k: "Lead (Pb)", v: "≤ 2.0 ppm" },
  { k: "Arsenic (As)", v: "≤ 1.0 ppm" },
  { k: "Cadmium (Cd)", v: "≤ 1.0 ppm" },
  { k: "Mercury (Hg)", v: "≤ 0.1 ppm" },
];

const PACKAGING =
  "25 kg net in food-grade multi-wall kraft paper bags with an inner food-grade LDPE/HDPE liner. 1 kg, 5 kg and custom retail or bulk formats, and private-label packing, available on request.";
const STORAGE =
  "Store in a cool, dry, hygienic place, away from direct sunlight, moisture and strong odours. Keep containers closed; reseal after opening.";
const ALLERGEN =
  "No declarable allergens per EU Reg. 1169/2011 and US FDA FALCPA. Gluten-free, vegan and non-GMO. Produced under GMP in a facility that also handles other plant products; cross-contact is controlled.";
const COMPLIANCE =
  "Sourced from FSSAI-licensed processing units following ISO 22000 / HACCP food-safety practices. Exported by an APEDA-registered, IEC-holding merchant exporter. Kosher, Halal, BRCGS and organic certification available against specific orders. No added preservatives or synthetic colour.";

export const categoryDefaults: Record<string, CategoryDefaults> = {
  "fruit-powders": {
    gradeLabel: "Food grade",
    shelfLife: "18–24 months from manufacture, in unopened, properly stored packaging",
    micro: MICRO_STD, heavyMetals: HEAVY_METALS,
    packaging: PACKAGING, storage: STORAGE, allergen: ALLERGEN, compliance: COMPLIANCE,
  },
  "culinary-spice-powders": {
    gradeLabel: "Food grade",
    shelfLife: "24 months from manufacture, in unopened, properly stored packaging",
    micro: MICRO_STD, heavyMetals: HEAVY_METALS,
    packaging: PACKAGING, storage: STORAGE, allergen: ALLERGEN, compliance: COMPLIANCE,
  },
  "functional-nutritional-powders": {
    gradeLabel: "Food grade",
    shelfLife: "18–24 months from manufacture, in unopened, properly stored packaging",
    micro: MICRO_STD, heavyMetals: HEAVY_METALS,
    packaging: PACKAGING, storage: STORAGE, allergen: ALLERGEN, compliance: COMPLIANCE,
  },
  "herbal-leaf-powders": {
    gradeLabel: "Food / nutraceutical grade",
    shelfLife: "24 months from manufacture, in unopened, properly stored packaging",
    micro: MICRO_HERBAL, heavyMetals: HEAVY_METALS,
    packaging: PACKAGING, storage: STORAGE, allergen: ALLERGEN, compliance: COMPLIANCE,
  },
  "hydrocolloids-food-additives": {
    gradeLabel: "Food grade (E-number where applicable)",
    shelfLife: "24 months from manufacture, in unopened, properly stored packaging",
    micro: MICRO_STD, heavyMetals: HEAVY_METALS,
    packaging: PACKAGING, storage: STORAGE, allergen: ALLERGEN, compliance: COMPLIANCE,
  },
};

// --- Per-product specifications ---------------------------------------------
export const productSpecs: Record<string, ProductSpec> = {
  // ---------------------------------------------------------------- FRUIT
  "guava-powder": {
    appearance: "Fine, free-flowing powder", colour: "Pale pink to cream",
    odour: "Characteristic musky-sweet guava", taste: "Sweet with a gentle tropical tartness",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Total ash", v: "≤ 4.0%" }],
    nutrition: { energy: 340, protein: 4.5, fat: 1.5, carb: 78, sugars: 55, fibre: 10, sodium: 15 },
    nutritionNote: "Natural source of vitamin C and dietary fibre.",
  },
  "pineapple-powder": {
    appearance: "Free-flowing powder", colour: "Pale golden-yellow",
    odour: "Fresh, tangy-sweet pineapple", taste: "Bright tangy-sweet tropical",
    mesh: "80–100 mesh (custom available)",
    nutrition: { energy: 350, protein: 3.0, fat: 0.8, carb: 85, sugars: 68, fibre: 4, sodium: 10 },
    nutritionNote: "Contributes natural vitamin C and manganese.",
  },
  "banana-powder": {
    appearance: "Fine powder", colour: "Creamy off-white to pale beige",
    odour: "Sweet, ripe banana", taste: "Mellow, naturally sweet",
    mesh: "80–100 mesh (custom available)",
    nutrition: { energy: 350, protein: 4.0, fat: 1.2, carb: 83, sugars: 45, fibre: 8, sodium: 3 },
    nutritionNote: "Naturally rich in potassium; adds body and smooth mouthfeel.",
  },
  "apple-powder": {
    appearance: "Free-flowing powder", colour: "Cream to pale tan",
    odour: "Sweet, orchard-fresh apple", taste: "Sweet-tart apple",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Naturally occurring pectin", v: "Present" }],
    nutrition: { energy: 340, protein: 1.5, fat: 1.0, carb: 86, sugars: 60, fibre: 10, sodium: 20 },
    nutritionNote: "Pectin-rich fruit fibre.",
  },
  "mango-powder": {
    appearance: "Free-flowing powder", colour: "Golden-yellow to amber",
    odour: "Rich, ripe mango", taste: "Sweet, full ripe-mango character",
    mesh: "80–100 mesh (custom available)",
    nutrition: { energy: 350, protein: 2.5, fat: 1.5, carb: 84, sugars: 70, fibre: 4, sodium: 15 },
    nutritionNote: "Natural source of vitamin A (beta-carotene) and vitamin C.",
  },
  "tamarind-powder": {
    appearance: "Free-flowing powder (de-seeded pulp)", colour: "Reddish-brown",
    odour: "Characteristic sour-sweet tamarind", taste: "Bold sour-sweet, tangy",
    mesh: "60–80 mesh (custom available)",
    params: [{ k: "Acidity (as tartaric acid)", v: "8–12%" }, { k: "pH (10% solution)", v: "2.5–3.5" }],
    nutrition: { energy: 300, protein: 3.5, fat: 0.6, carb: 75, sugars: 40, fibre: 6, sodium: 30 },
    nutritionNote: "Natural plant acids (tartaric acid).",
  },
  "papaya-powder": {
    appearance: "Fine, smooth powder", colour: "Orange to pale orange",
    odour: "Mild, sweet tropical", taste: "Soft, sweet papaya",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Naturally occurring enzymes", v: "Papain (native)" }],
    nutrition: { energy: 340, protein: 4.0, fat: 0.9, carb: 82, sugars: 55, fibre: 9, sodium: 20 },
    nutritionNote: "Source of natural enzymes, vitamin A and vitamin C.",
  },
  "pomegranate-powder": {
    appearance: "Free-flowing powder", colour: "Deep red to maroon",
    odour: "Sweet-tart pomegranate", taste: "Sweet-tart, fruity",
    mesh: "80–100 mesh (custom available)",
    nutrition: { energy: 330, protein: 3.0, fat: 1.5, carb: 80, sugars: 60, fibre: 5, sodium: 10 },
    nutritionNote: "Rich in natural antioxidants (punicalagins) and vitamin C.",
  },

  // ---------------------------------------------------------------- HERBAL & LEAF
  "amla-powder": {
    appearance: "Fine powder", colour: "Light brown to beige",
    odour: "Characteristic, mildly sour", taste: "Sharply sour and astringent",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Vitamin C (typical)", v: "≥ 1.5%" }, { k: "Tannins", v: "Present (native)" }],
    nutrition: { energy: 315, protein: 5.0, fat: 1.5, carb: 70, sugars: 20, fibre: 30, sodium: 20 },
    nutritionNote: "One of nature's richest plant sources of vitamin C.",
  },
  "amchur-powder": {
    appearance: "Fine powder (sun-dried green mango)", colour: "Pale beige to light tan",
    odour: "Sharp, sour green-mango", taste: "Sour, tangy and cooling",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Vitamin C (typical)", v: "Naturally present" }, { k: "Acidity", v: "High (plant acids)" }],
    nutrition: { energy: 330, protein: 3.0, fat: 1.0, carb: 78, sugars: 35, fibre: 12, sodium: 25 },
    nutritionNote: "Traditional Ayurvedic digestive; natural vitamin C and antioxidants.",
  },
  "moringa-powder": {
    appearance: "Fine leaf powder", colour: "Deep green",
    odour: "Green, leafy, matcha-like", taste: "Earthy with a mild green bitterness",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Iron (typical)", v: "25–30 mg/100 g" }, { k: "Calcium (typical)", v: "1,800–2,000 mg/100 g" }],
    nutrition: { energy: 350, protein: 27, fat: 5, carb: 45, sugars: 8, fibre: 20, sodium: 150 },
    nutritionNote: "Nutrient-dense: plant protein, iron, calcium, vitamin A and vitamin C.",
  },
  "curry-leaf-powder": {
    appearance: "Fine leaf powder", colour: "Dark green",
    odour: "Aromatic curry-leaf, faintly citrus", taste: "Savoury, herbal with light bitterness",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Volatile aroma oils", v: "Native" }],
    nutrition: { energy: 340, protein: 15, fat: 6, carb: 55, sugars: 5, fibre: 25, sodium: 50 },
    nutritionNote: "Source of iron and calcium; carries the leaf's natural aroma oils.",
  },
  "tulsi-powder": {
    appearance: "Fine leaf powder", colour: "Green to deep green",
    odour: "Aromatic, clove-like herbal", taste: "Warm, peppery-herbal",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Essential oils (eugenol)", v: "Native" }],
    nutrition: { energy: 330, protein: 18, fat: 4, carb: 50, sugars: 6, fibre: 22, sodium: 40 },
    nutritionNote: "Adaptogenic herb rich in natural antioxidants and essential oils.",
  },

  // ---------------------------------------------------------------- CULINARY & SPICE
  "red-onion-powder": {
    appearance: "Powder (granules & kibbled available)", colour: "Pink-cream to light pink",
    odour: "Pungent, characteristic onion", taste: "Strong, savoury onion",
    mesh: "80–100 mesh (also granules / minced / kibbled)",
    params: [{ k: "Total ash", v: "≤ 5.0%" }, { k: "Acid-insoluble ash", v: "≤ 0.5%" }, { k: "Added sulphur (SO₂)", v: "None (≤ 20 ppm)" }],
    nutrition: { energy: 350, protein: 10, fat: 1.5, carb: 78, sugars: 38, fibre: 12, sodium: 40 },
    nutritionNote: "No added sulphur; concentrated natural onion flavour.",
  },
  "pink-onion-powder": {
    appearance: "Powder (granules & kibbled available)", colour: "Pinkish-cream",
    odour: "Pungent, characteristic onion", taste: "Savoury onion, balanced pungency",
    mesh: "80–100 mesh (also granules / minced / kibbled)",
    params: [{ k: "Total ash", v: "≤ 5.0%" }, { k: "Acid-insoluble ash", v: "≤ 0.5%" }, { k: "Added sulphur (SO₂)", v: "None (≤ 20 ppm)" }],
    nutrition: { energy: 350, protein: 10, fat: 1.5, carb: 78, sugars: 38, fibre: 12, sodium: 40 },
    nutritionNote: "No added sulphur; concentrated natural onion flavour.",
  },
  "white-onion-powder": {
    appearance: "Powder (granules & kibbled available)", colour: "Creamy white to pale cream",
    odour: "Pungent, characteristic onion", taste: "Clean, savoury onion",
    mesh: "80–100 mesh (also granules / minced / kibbled)",
    params: [{ k: "Total ash", v: "≤ 5.0%" }, { k: "Acid-insoluble ash", v: "≤ 0.5%" }, { k: "Added sulphur (SO₂)", v: "None (≤ 20 ppm)" }],
    nutrition: { energy: 350, protein: 10, fat: 1.5, carb: 78, sugars: 38, fibre: 12, sodium: 40 },
    nutritionNote: "No added sulphur; light colour for pale sauces and blends.",
  },
  "garlic-powder": {
    appearance: "Powder (granules & minced available)", colour: "Creamy white to off-white",
    odour: "Strong, pungent garlic", taste: "Sharp, savoury garlic",
    mesh: "80–100 mesh (also granules / minced)",
    params: [{ k: "Total ash", v: "≤ 5.5%" }, { k: "Acid-insoluble ash", v: "≤ 0.5%" }, { k: "Added sulphur (SO₂)", v: "None (≤ 20 ppm)" }],
    nutrition: { energy: 345, protein: 16, fat: 1.0, carb: 73, sugars: 15, fibre: 9, sodium: 30 },
    nutritionNote: "Carefully dried to preserve natural garlic pungency (allicin).",
  },
  "ginger-powder": {
    appearance: "Fine powder", colour: "Pale yellow to buff",
    odour: "Warm, pungent ginger", taste: "Hot, pungent and aromatic",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Volatile oil", v: "≥ 1.5% v/w" }, { k: "Total ash", v: "≤ 6.0%" }],
    nutrition: { energy: 335, protein: 9, fat: 4, carb: 72, sugars: 3, fibre: 14, sodium: 30 },
    nutritionNote: "Retains natural gingerols and volatile aroma oils.",
  },
  "green-chilli-powder": {
    appearance: "Powder (coarse cut available)", colour: "Green to olive-green",
    odour: "Pungent, fresh green-chilli", taste: "Hot and sharp",
    mesh: "40–60 mesh / 80 mesh",
    params: [{ k: "Pungency (typical)", v: "15,000–30,000 SHU (grade-dependent)" }, { k: "Total ash", v: "≤ 8.0%" }],
    nutrition: { energy: 320, protein: 13, fat: 6, carb: 56, sugars: 10, fibre: 28, sodium: 30 },
    nutritionNote: "Natural source of vitamin C and capsaicinoids.",
  },
  "fried-onion": {
    appearance: "Crisp fried onion strands / flakes (birista)", colour: "Golden brown",
    odour: "Sweet, caramelised fried onion", taste: "Sweet-savoury, crunchy",
    mesh: "Flakes / strands (not milled)",
    params: [{ k: "Frying medium", v: "Palm / sunflower oil (specify)" }, { k: "Total fat", v: "30–38%" }],
    nutrition: { energy: 520, protein: 6, fat: 35, carb: 45, sugars: 20, fibre: 6, sodium: 50 },
    nutritionNote: "Ready-to-use garnish; fat content reflects the frying medium.",
  },

  // ---------------------------------------------------------------- FUNCTIONAL & NUTRITIONAL
  "lemon-powder": {
    appearance: "Fine powder", colour: "Pale yellow to cream",
    odour: "Fresh, zesty citrus", taste: "Sour, tangy citrus",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Citric acidity", v: "Naturally high" }, { k: "Vitamin C", v: "Naturally present" }],
    nutrition: { energy: 300, protein: 5, fat: 2, carb: 68, sugars: 10, fibre: 12, sodium: 15 },
    nutritionNote: "Natural citric acid and vitamin C for tang and clean-label acidification.",
  },
  "beetroot-powder": {
    appearance: "Fine powder", colour: "Deep red-purple (magenta)",
    odour: "Earthy-sweet beet", taste: "Sweet and earthy",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Natural colour (betalains)", v: "High tinctorial strength" }, { k: "Naturally occurring nitrates", v: "Present" }],
    nutrition: { energy: 330, protein: 9, fat: 1, carb: 75, sugars: 55, fibre: 10, sodium: 250 },
    nutritionNote: "Natural red-purple colourant (betalains) and dietary nitrates.",
  },
  "tomato-powder": {
    appearance: "Free-flowing powder (spray/drum-dried)", colour: "Red to brick-red",
    odour: "Concentrated ripe tomato", taste: "Tangy-sweet, umami tomato",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Lycopene", v: "Naturally present" }, { k: "Carrier (if spray-dried)", v: "With / without maltodextrin (specify)" }],
    nutrition: { energy: 300, protein: 12, fat: 2, carb: 62, sugars: 40, fibre: 12, sodium: 150 },
    nutritionNote: "Rich in lycopene; delivers natural tomato colour and umami.",
  },
  "carrot-powder": {
    appearance: "Fine powder", colour: "Orange",
    odour: "Sweet, characteristic carrot", taste: "Sweet and earthy",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Beta-carotene (pro-vitamin A)", v: "Naturally high" }],
    nutrition: { energy: 330, protein: 7, fat: 1.5, carb: 76, sugars: 40, fibre: 20, sodium: 200 },
    nutritionNote: "Natural source of beta-carotene (vitamin A) and colour.",
  },
  "jackfruit-powder": {
    appearance: "Free-flowing powder", colour: "Pale yellow to cream",
    odour: "Sweet, characteristic jackfruit", taste: "Mild, sweet and tropical",
    mesh: "80–100 mesh (custom available)",
    nutrition: { energy: 350, protein: 5, fat: 1, carb: 84, sugars: 45, fibre: 8, sodium: 10 },
    nutritionNote: "Natural source of potassium and vitamin C.",
  },
  "coriander-leaf-powder": {
    appearance: "Fine leaf powder", colour: "Vivid green",
    odour: "Fresh, citrusy coriander (cilantro)", taste: "Herbaceous, bright citrusy",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Volatile aroma oils", v: "Native" }],
    nutrition: { energy: 330, protein: 20, fat: 5, carb: 50, sugars: 6, fibre: 22, sodium: 40 },
    nutritionNote: "Source of vitamin A, vitamin K and iron; carries the leaf's fresh aroma oils.",
  },
  "mint-powder": {
    appearance: "Fine leaf powder", colour: "Deep green",
    odour: "Cooling, fresh mint (menthol)", taste: "Cooling, minty with mild bitterness",
    mesh: "80–100 mesh (custom available)",
    params: [{ k: "Menthol / volatile oils", v: "Native" }],
    nutrition: { energy: 320, protein: 18, fat: 5, carb: 52, sugars: 6, fibre: 24, sodium: 45 },
    nutritionNote: "Carries the leaf's natural menthol and volatile aroma oils; source of vitamin A.",
  },

  // ---------------------------------------------------------------- HYDROCOLLOIDS
  "guar-gum-powder": {
    appearance: "Free-flowing powder", colour: "White to creamy-white / pale yellow",
    odour: "Odourless to near-neutral", taste: "Bland, neutral",
    mesh: "200 mesh (100 mesh available)",
    params: [
      { k: "Viscosity (1% soln, 25 °C)", v: "3,500–8,000 cps (grade-dependent)" },
      { k: "Galactomannan (gum) content", v: "≥ 80%" },
      { k: "pH (1% solution)", v: "5.5–7.0" },
      { k: "Protein", v: "≤ 5.0%" },
      { k: "Acid-insoluble residue", v: "≤ 4.0%" },
      { k: "CAS No. / INS", v: "9000-30-0 / E412" },
    ],
    nutrition: { energy: 200, protein: 4, fat: 0.5, carb: 80, sugars: 0, fibre: 80, sodium: 20 },
    nutritionNote: "Almost entirely soluble dietary fibre; used as a thickener/stabiliser.",
  },
  "psyllium-husk-powder": {
    appearance: "Powder / fine husk", colour: "Off-white to cream (light brown husk)",
    odour: "Neutral, faintly earthy", taste: "Bland, mucilaginous",
    mesh: "40 / 100 mesh (specify)",
    params: [
      { k: "Purity", v: "99% (95% / 98% grades available)" },
      { k: "Swelling volume (mucilage)", v: "≥ 40 ml/g" },
      { k: "Light extraneous matter", v: "≤ 1.0%" },
    ],
    nutrition: { energy: 200, protein: 2, fat: 0.5, carb: 85, sugars: 0, fibre: 80, sodium: 20 },
    nutritionNote: "Very high soluble-fibre content; forms a gel on hydration.",
  },
  "tamarind-kernel-powder": {
    appearance: "Powder", colour: "Cream to light brown",
    odour: "Mild, characteristic", taste: "Bland",
    mesh: "100 mesh (custom available)",
    params: [
      { k: "Viscosity", v: "High (grade-dependent)" },
      { k: "Cold / hot water solubility", v: "Swells cold, disperses hot" },
      { k: "Protein", v: "12–18%" },
    ],
    nutrition: { energy: 340, protein: 15, fat: 5, carb: 65, sugars: 5, fibre: 8, sodium: 20 },
    nutritionNote: "Plant-based thickener and sizing agent (polysaccharide-rich).",
  },
  "cassia-gum-powder": {
    appearance: "Free-flowing powder", colour: "Pale yellow to cream",
    odour: "Neutral", taste: "Bland",
    mesh: "200 mesh (custom available)",
    params: [
      { k: "Viscosity", v: "Grade-dependent" },
      { k: "Purity (polysaccharide)", v: "≥ 75%" },
      { k: "INS", v: "E427" },
    ],
    nutrition: { energy: 200, protein: 5, fat: 0.5, carb: 80, sugars: 0, fibre: 75, sodium: 20 },
    nutritionNote: "Galactomannan gum used as a thickener/stabiliser (food-grade).",
  },
};
